sudo: required
services:
  - docker

before_install:
  - docker build -t muyassarov/react-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true muyassarov/react-complex-test npm test

after_success:
  - docker build -t muyassarov/multi-client ./client
  - docker build -t muyassarov/multi-nginx ./nginx
  - docker build -t muyassarov/multi-server ./server
  - docker build -t muyassarov/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push muyassarov/multi-client 
  - docker push muyassarov/multi-nginx
  - docker push muyassarov/multi-server
  - docker push muyassarov/multi-worker
  